project_id = "kinwixjeoghoeoubnoln"

[functions.quiz-questions]
verify_jwt = false

[functions.quiz-submit]
verify_jwt = true

[functions.get-matches]
verify_jwt = true

[functions.me]
verify_jwt = true

[functions.conversations]
verify_jwt = true

[functions.messages]
verify_jwt = true
