// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kinwixjeoghoeoubnoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbndpeGplb2dob2VvdWJub2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODU3NTgsImV4cCI6MjA3NTI2MTc1OH0.vGK_g5vW-HgikWn30ZwyZhLrty5vw2xXF_NoBBgrfks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});